version: '3.1'

services: 

  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network  
    volumes:
     - mariadb-data:/var/lib/mysql

  geninventory:
    image: gen_inv:v4
    ports:
      - 8065:80
    networks: 
      - internal-container-network
    volumes:
     - sqldata:/root/.aspnet/DataProtection-Keys
    depends_on: 
       - db
   
volumes:
  sqldata:
  mariadb-data:

networks:
  internal-container-network:
    driver: bridge